FROM registry.suse.com/bci/bci-base:latest
ENV ZYPPERCMD="zypper --non-interactive"

# requirements 
RUN $ZYPPERCMD install python3 python3-devel wget awk

# build
COPY --chmod=0700 install-miniconda.sh ./
COPY --chmod=0700 install-vllm.sh ./
RUN sh install-miniconda.sh
RUN sh install-vllm.sh
